const clinicalTrials = {
    "clinicalTrials": 
    [
        {
            "id": 0,
            "image": "<PATH_TO_IMAGE_HERE>",
            "dateSubmitted": "10/08/2022",
            "header": "Cancer Study",
            "title": "A study for patient with terminal stage 3 cancer",
            "minAge": 18,
            "maxAge": 70,
            "hospital": "Rigshospitalet",
            "streetName": "Tagensvej",
            "doorNumber": 44,
            "zipCode": 2100,
            "city": "Copenhagen",
            "region": "Hovedstaden",
            "county": "Denmark",
            "match": ["Cancer"],
            "cardDescription": "Cancer research studies look for and find better ways to prevent, diagnose, and treat cancer. Doctors and scientists can design these studies in many ways to answer the questions they have. No study design is perfect. Each has strengths and limits.",
            "longDescription": "In observational studies, researchers have less control over the people in the study. This means that certain factors could affect the results. However, these studies provide data that can help guide future research. Types of observational studies include: Case-control studies. These studies compare 2 groups of people. For instance, researchers could compare information about people with cancer and those who do not have cancer. People who have cancer are the case group. People who do not have cancer are then the control group. Researchers may look for lifestyle or genetic differences between the groups. By doing this, they hope to find out why one group has a disease and the other group does not. These studies are called retrospective. That means researchers study an event that has already occurred. Cohort studies. These studies are prospective. That means researchers study an event as it occurs. They watch a group of volunteers for a long period of time and track something. For instance, they could track any new cancer diagnoses. This type of study can look at whether certain nutrients, exercise, or other action can prevent cancer. This approach can also find cancer risk factors. For instance, cohort studies have looked at whether postmenopausal hormone replacement therapy increases the risk of breast cancer. Case reports and case series. Case reports are detailed reports of one person's medical history. If many people receive a similar treatment, the reports may be grouped into a case series. The results of case series studies are descriptions of patients' histories within a specific group. As such, doctors should not use them to choose treatment options. But case reports can help doctors think of new ideas for research studies in the future. Cross-sectional studies. These studies look at how diseases interact with other factors within a specific group at one point in time. For example, a study might evaluate how patients who took a certain medication are doing ten years later to see who has and has not developed cancer. Because these studies only measure a point in time, they cannot prove that something causes cancer, but they can help scientists with future research.",
            "ownerId": 0,
            "days": 3,
            "time": "16:20 - 17:20",
            "participants": ["List of participants"]
        },

        {
            "id": 1,
            "image": "<PATH_TO_IMAGE_HERE>",
            "dateSubmitted": "10/08/2022",
            "header": "Diabetis 2 study",
            "title": "Help us solv insuline resistance problem",
            "minAge": 18,
            "maxAge": 70,
            "hospital": "Rigshospitalet",
            "streetName": "Tagensvej",
            "doorNumber": 44,
            "zipCode": 2100,
            "city": "Copenhagen",
            "region": "Hovedstaden",
            "county": "Sweden",
            "match": ["Cancer"],
            "cardDescription": "The purposes of this study are to determine:  (a) if there is a relationship between the extent that the individual mode of human agency is employed and the quality of diabetes control among adults who have been diagnosed with DM2 for at least one year; and (b) if there is a relationship between the extent that the proxy mode of human agency is employed and quality of diabetes control among adults who have been diagnosed with DM2 for at least one year. ",
            "longDescription": "In observational studies, researchers have less control over the people in the study. This means that certain factors could affect the results. However, these studies provide data that can help guide future research. Types of observational studies include: Case-control studies. These studies compare 2 groups of people. For instance, researchers could compare information about people with cancer and those who do not have cancer. People who have cancer are the case group. People who do not have cancer are then the control group. Researchers may look for lifestyle or genetic differences between the groups. By doing this, they hope to find out why one group has a disease and the other group does not. These studies are called retrospective. That means researchers study an event that has already occurred. Cohort studies. These studies are prospective. That means researchers study an event as it occurs. They watch a group of volunteers for a long period of time and track something. For instance, they could track any new cancer diagnoses. This type of study can look at whether certain nutrients, exercise, or other action can prevent cancer. This approach can also find cancer risk factors. For instance, cohort studies have looked at whether postmenopausal hormone replacement therapy increases the risk of breast cancer. Case reports and case series. Case reports are detailed reports of one person's medical history. If many people receive a similar treatment, the reports may be grouped into a case series. The results of case series studies are descriptions of patients' histories within a specific group. As such, doctors should not use them to choose treatment options. But case reports can help doctors think of new ideas for research studies in the future. Cross-sectional studies. These studies look at how diseases interact with other factors within a specific group at one point in time. For example, a study might evaluate how patients who took a certain medication are doing ten years later to see who has and has not developed cancer. Because these studies only measure a point in time, they cannot prove that something causes cancer, but they can help scientists with future research.",
            "ownerId": 0,
            "days": 3,
            "time": "16:20 - 17:20",
            "participants": ["List of participants"]
        },

        {
            "id": 2,
            "image": "<PATH_TO_IMAGE_HERE>",
            "dateSubmitted": "10/08/2022",
            "header": "Bone fraction",
            "title": "A study for patient with terminal stage 3 cancer",
            "minAge": 18,
            "maxAge": 70,
            "hospital": "Rigshospitalet",
            "streetName": "Tagensvej",
            "doorNumber": 44,
            "zipCode": 2100,
            "city": "Copenhagen",
            "region": "Hovedstaden",
            "county": "Denmark",
            "match": ["Cancer"],
            "cardDescription": "Cancer research studies look for and find better ways to prevent, diagnose, and treat cancer. Doctors and scientists can design these studies in many ways to answer the questions they have. No study design is perfect. Each has strengths and limits.",
            "longDescription": "In observational studies, researchers have less control over the people in the study. This means that certain factors could affect the results. However, these studies provide data that can help guide future research. Types of observational studies include: Case-control studies. These studies compare 2 groups of people. For instance, researchers could compare information about people with cancer and those who do not have cancer. People who have cancer are the case group. People who do not have cancer are then the control group. Researchers may look for lifestyle or genetic differences between the groups. By doing this, they hope to find out why one group has a disease and the other group does not. These studies are called retrospective. That means researchers study an event that has already occurred. Cohort studies. These studies are prospective. That means researchers study an event as it occurs. They watch a group of volunteers for a long period of time and track something. For instance, they could track any new cancer diagnoses. This type of study can look at whether certain nutrients, exercise, or other action can prevent cancer. This approach can also find cancer risk factors. For instance, cohort studies have looked at whether postmenopausal hormone replacement therapy increases the risk of breast cancer. Case reports and case series. Case reports are detailed reports of one person's medical history. If many people receive a similar treatment, the reports may be grouped into a case series. The results of case series studies are descriptions of patients' histories within a specific group. As such, doctors should not use them to choose treatment options. But case reports can help doctors think of new ideas for research studies in the future. Cross-sectional studies. These studies look at how diseases interact with other factors within a specific group at one point in time. For example, a study might evaluate how patients who took a certain medication are doing ten years later to see who has and has not developed cancer. Because these studies only measure a point in time, they cannot prove that something causes cancer, but they can help scientists with future research.",
            "ownerId": 0,
            "days": 3,
            "time": "16:20 - 17:20",
            "participants": ["List of participants"]
        },
        {
            "id": 3,
            "image": "<PATH_TO_IMAGE_HERE>",
            "dateSubmitted": "10/08/2022",
            "header": "Brain Cancer",
            "title": "A study for patient with terminal stage 3 cancer",
            "minAge": 18,
            "maxAge": 70,
            "hospital": "Rigshospitalet",
            "streetName": "Tagensvej",
            "doorNumber": 44,
            "zipCode": 2100,
            "city": "Copenhagen",
            "region": "Hovedstaden",
            "county": "Denmark",
            "match": ["Cancer"],
            "cardDescription": "Cancer research studies look for and find better ways to prevent, diagnose, and treat cancer. Doctors and scientists can design these studies in many ways to answer the questions they have. No study design is perfect. Each has strengths and limits.",
            "longDescription": "In observational studies, researchers have less control over the people in the study. This means that certain factors could affect the results. However, these studies provide data that can help guide future research. Types of observational studies include: Case-control studies. These studies compare 2 groups of people. For instance, researchers could compare information about people with cancer and those who do not have cancer. People who have cancer are the case group. People who do not have cancer are then the control group. Researchers may look for lifestyle or genetic differences between the groups. By doing this, they hope to find out why one group has a disease and the other group does not. These studies are called retrospective. That means researchers study an event that has already occurred. Cohort studies. These studies are prospective. That means researchers study an event as it occurs. They watch a group of volunteers for a long period of time and track something. For instance, they could track any new cancer diagnoses. This type of study can look at whether certain nutrients, exercise, or other action can prevent cancer. This approach can also find cancer risk factors. For instance, cohort studies have looked at whether postmenopausal hormone replacement therapy increases the risk of breast cancer. Case reports and case series. Case reports are detailed reports of one person's medical history. If many people receive a similar treatment, the reports may be grouped into a case series. The results of case series studies are descriptions of patients' histories within a specific group. As such, doctors should not use them to choose treatment options. But case reports can help doctors think of new ideas for research studies in the future. Cross-sectional studies. These studies look at how diseases interact with other factors within a specific group at one point in time. For example, a study might evaluate how patients who took a certain medication are doing ten years later to see who has and has not developed cancer. Because these studies only measure a point in time, they cannot prove that something causes cancer, but they can help scientists with future research.",
            "ownerId": 0,
            "days": 3,
            "time": "16:20 - 17:20",
            "participants": ["List of participants"]
        }
    ]
}
export default clinicalTrials